Repository Mu2e/Production, pull requests merged in 2022-05, with the labels that each got.

#177 Use DB in digitization and reco
  JobConfig/digitize/epilog.fcl
  JobConfig/mixing/NoPrimary.fcl
  JobConfig/reco/epilog.fcl
  Scripts/gen_Digitize.sh
  Scripts/gen_Mix.sh
  Scripts/gen_Reco.sh
  Validation/ceDigi.fcl
  Validation/ceMix.fcl
  Validation/ceSimReco.fcl
  Validation/cosmicOffSpill.fcl
  Validation/cosmicSimReco.fcl
  Validation/database.fcl
  Validation/potSim.fcl
  Validation/reco.fcl
Labels: build finished

#178 Change validation purpose to 'best'.
  Scripts/gen_Reco.sh
  Validation/ceSimReco.fcl
  Validation/ceSteps.fcl
  Validation/cosmicOffSpill.fcl
  Validation/cosmicSimReco.fcl
  Validation/database.fcl
Labels: build finished

#179 Making scripts executables
  Scripts/gen_CosmicStage2.sh
  Scripts/gen_NoPrimary.sh
  Scripts/gen_POT_infinite.sh
  Scripts/gen_PiBeamResampler.sh
  Scripts/gen_PionBeamSelector.sh
  Scripts/gen_PionStops.sh
  Scripts/gen_Primary.sh
Labels: build finished

#181 Fixinc
  JobConfig/primary/NoPrimary.fcl
  Scripts/gen_BeamSplitter.sh
  Scripts/gen_EleBeamResampler.sh
  Scripts/gen_Mix.sh
  Scripts/gen_MuBeamResampler.sh
  Scripts/gen_MuStopPileup.sh
  Scripts/gen_MuonStops.sh
  Scripts/gen_NeutralsResampler.sh
  Scripts/gen_NoPrimary.sh
  Scripts/gen_NoPrimaryPBISequence.sh
  Scripts/gen_POT.sh
  Scripts/gen_Primary.sh
Labels: build finished

#182 S2fix
  JobConfig/cosmic/S2Resampler.fcl
Labels: build running

#183 fixed gen_mix for noprimary
  Scripts/gen_Mix.sh
Labels: build finished

#184 Add database
  Validation/reco.fcl
Labels: build finished

#185 Add script to split IPA stops
  JobConfig/pileup/IPAStopSelector.fcl
Labels: build finished

#186 Moving from IPAStopResampler to IPAMuminusStopResampler
  JobConfig/primary/IPAMuminusFlateMinus.fcl
  JobConfig/primary/IPAMuminusMichel.fcl
  JobConfig/primary/IPAStopParticle.fcl
  JobConfig/primary/prolog.fcl
  Tests/IPAFlatSteps.fcl
  Tests/IPAMichelSteps.fcl
Labels: build pending
