Repository Mu2e/Production, pull requests merged in 2025-01, with the labels that each got.

#379 Updates and fixes
  Documents/pass1.dot
  Documents/pass1.pdf
Labels: build running

#383 Add a test stopping target antiproton processing for studies
  JobConfig/beam/SimpleAntiprotons.fcl
  JobConfig/primary/AntiprotonStop.fcl
  Tests/AntiprotonStopSteps.fcl
Labels: build finished

#382 Add flat RMC photon conversion saving production fcl
  JobConfig/primary/RMCFlatGammaReader.fcl
  JobConfig/primary/RMCFlatGammaWriter.fcl
  JobConfig/primary/prolog.fcl
  Tests/RMCFlatGammaWriter.fcl
Labels: build finished

#384 Various additions to production scripts
  CampaignConfig/mdc2020_digireco.cfg
  CampaignConfig/mdc2020_prolog.cfg
  CampaignConfig/wideband_crv.cfg
  CampaignConfig/wideband_crv.ini
  ProjPy/gen_Campaigns.py
  ProjPy/mdc2020_mixing.ini
  ProjPy/mdc2020_reco.ini
  Scripts/gen_Merge.sh
  Scripts/inspect_datasets.py
  Scripts/run_RecoEntuple.py
  Scripts/run_mu2ejobfcl.py
  data/mix_cosmic.json
Labels: build finished

#375 Unified on and offspill trigger
  JobConfig/digitize/Digitize.fcl
  JobConfig/digitize/Extracted.fcl
  JobConfig/digitize/MakeSurfaceSteps.fcl
  JobConfig/digitize/NoField.fcl
  JobConfig/digitize/OffSpill.fcl
  JobConfig/digitize/OffSpill_epilog.fcl
  JobConfig/digitize/OnSpill.fcl
  JobConfig/digitize/Spill.fcl
  JobConfig/digitize/prolog.fcl
  JobConfig/mixing/Mix.fcl
Labels: build finished

#387 Oksuzian111224a
  CampaignConfig/mdc2020_digireco.cfg
  CampaignConfig/mdc2020_primary.cfg
  CampaignConfig/mdc2020_prolog.cfg
  JobConfig/pbar/PbarSTGunStops.fcl
  JobConfig/primary/PbarResampling.fcl
  ProjPy/gen_Campaigns.py
  ProjPy/mdc2020_primary.ini
  Scripts/gen_Primary.sh
  Scripts/remove_sam_locations.py
  Scripts/run_JITfcl.py
Labels: build pending

#386 Add trigger MC truth matching to digitization
  JobConfig/digitize/OnSpill.fcl
  JobConfig/digitize/OnSpill_epilog.fcl
  JobConfig/digitize/epilog.fcl
  JobConfig/digitize/prolog.fcl
  JobConfig/digitize/trigSequencesMC.fcl
  JobConfig/mixing/Mix.fcl
  JobConfig/mixing/prolog.fcl
  JobConfig/primary/prolog.fcl
  JobConfig/reco/prolog.fcl
  Validation/ceDigi.fcl
  Validation/ceMix.fcl
  Validation/ceSimReco.fcl
  Validation/cosmicSimReco.fcl
Labels: build pending

#388 Oksuzian111224a
  CampaignConfig/mdc2020_primary.cfg
  ProjPy/mdc2020_primary.ini
  Scripts/POMS/upload_ini.py
  Scripts/gen_Resampler.sh
  data/primary_pbar.json
  data/primary_rmc.json
Labels: build pending

#390 minor bug fix in the name for gen_Resampler.sh
  CampaignConfig/mdc2020_primary.cfg
Labels: build finished

#389 Tweak OffSpill digitization
  JobConfig/digitize/Extracted.fcl
  JobConfig/digitize/MakeSurfaceSteps.fcl
  JobConfig/digitize/NoField.fcl
  JobConfig/digitize/OffSpill.fcl
  JobConfig/digitize/OnSpill.fcl
  JobConfig/digitize/Spill.fcl
  JobConfig/digitize/epilog.fcl
  JobConfig/digitize/prolog.fcl
  JobConfig/mixing/Mix.fcl
  Validation/ceDigi.fcl
  Validation/ceMix.fcl
  Validation/cosmicOffSpill.fcl
Labels: build finished

#391 No need to check for cvmfs directory.
  Scripts/gen_Resampler.sh
  data/primary_rmc.json
Labels: build finished

#392 Minor tweaks to mix and digi campaigns
  CampaignConfig/mdc2020_digireco.cfg
  ProjPy/mdc2020_digireco.ini
  ProjPy/mdc2020_mixing.ini
  ProjPy/mdc2020_primary.ini
  Scripts/gen_Reco.sh
  data/digi_cosmic.json
  data/digi_cosmic_calib.json
  data/digi_cosmic_signal.json
  data/mix_ce.json
  data/mix_cosmic.json
Labels: build pending

#393 Changes to S1 in the preparation for ExtractedCRY production
  JobConfig/cosmic/ExtractedCRY.fcl
  JobConfig/cosmic/prolog.fcl
  Scripts/gen_S1.sh
Labels: build finished
