Repository Mu2e/Production, pull requests merged in 2025-05, with the labels that each got.

#427 Add production scripts for physical RPC spectra
  JobConfig/primary/RPC.fcl
  JobConfig/primary/RPCExternalPhysical.fcl
  JobConfig/primary/RPCInternalPhysical.fcl
  JobConfig/primary/RPCPhysical.fcl
  JobConfig/primary/TargetPiStopParticle.fcl
Labels: build failed

#428 Update accept/reject filter configuration
  JobConfig/primary/RPCPhysical.fcl
Labels: build finished

#430 Addition of json2jobdef.sh
  CampaignConfig/mdc2020_digireco.cfg
  Scripts/json2jobdef.sh
  data/merge_filter.json
  data/resampler.json
  data/stage1.json
Labels: build pending

#431 remove OnSpill filtering
  .gitignore
  JobConfig/reco/OnSpill.fcl
  JobConfig/recoMC/OnSpill.fcl
Labels: build finished

#425 Add MDS validation
  JobConfig/digitize/AddSurfaceSteps.fcl
  JobConfig/digitize/Digitize.fcl
  JobConfig/digitize/prolog.fcl
  JobConfig/reco/Reco.fcl
  JobConfig/recoMC/Reco.fcl
  Scripts/nightly_jobs.sh
  Validation/nightly/CeMix/build_jobs.sh
  Validation/nightly/CeSimReco/build_jobs.sh
  Validation/nightly/CeSimReco/digitize.fcl
  Validation/nightly/CeSimReco/reconstructCeMinus.fcl
  Validation/nightly/CeSimReco/reconstructCePlus.fcl
  Validation/nightly/CosmicSimReco/S2.fcl
  Validation/nightly/CosmicSimReco/build_jobs.sh
  Validation/nightly/CosmicSimReco/digitizeOffSpill.fcl
  Validation/nightly/CosmicSimReco/digitizeOnSpill.fcl
  Validation/nightly/CosmicSimReco/reconstructOffSpill.fcl
  Validation/nightly/CosmicSimReco/reconstructOnSpill.fcl
  Validation/nightly/MDS/build_jobs.sh
  Validation/nightly/MDS/digitize.fcl
  Validation/nightly/MDS/reconstruct.fcl
  Validation/nightly/Pileup/build_jobs.sh
  Validation/nightly/Trigger/build_jobs.sh
  Validation/nightly/Trigger/trigger.fcl
Labels: build pending

#432 Changes to productions scripts - mainly RPC jobs
  CampaignConfig/mdc2020_prolog.cfg
  Scripts/json2jobdef.sh
  Scripts/run_JITfcl.py
  data/resampler.json
  data/stage1.json
Labels: build pending

#433 Accept vertical line fits
  JobConfig/reco/prolog.fcl
Labels: build running
